server.port=${PORT:8080}
logging.level.org.atmosphere=warn

# Launch the default browser when starting the application in development mode
vaadin.launch-browser=true

# To improve the performance during development.
# For more information https://vaadin.com/docs/latest/flow/integrations/spring/configuration#special-configuration-parameters
vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,com.murali


spring.datasource.url=jdbc:postgresql://localhost:5432/comp1
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.file.name=logs/leave-management-system.log
logging.level.root=INFO
logging.level.com.murali=INFO 

# 3. Format of the log messages in the file
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

# 4. Format of the log messages in the console (Optional)
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%thread]){magenta} %clr(%-5level){} %clr(%logger{36}){cyan} - %msg%n

logging.logback.rollingpolicy.max-history=30

# Maximum size of all log files combined before deleting oldest ones
logging.logback.rollingpolicy.total-size-cap=100MB